# Generated by Django 5.2.2 on 2025-06-12 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_casoadoptado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoadoptado',
            name='mascota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adopciones.mascota'),
        ),
    ]
