# Generated by Django 5.2.2 on 2025-06-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_alter_casoadoptado_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoadoptado',
            name='adoptante_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
