# Generated by Django 5.2.2 on 2025-06-22 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0005_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='adopciones.mensajecontacto'),
        ),
    ]
