# Generated by Django 5.2.2 on 2025-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0006_mensajecontacto_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoadoptado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
